
plugins:
  mall_enabled:
    default: true
    client: true
  mall_route_prefix:
    default: "mall"
    client: true
  mall_currency:
    default: "CNY"
    client: true
  mall_wechat_enabled:
    default: true
    client: true
  mall_paypal_enabled:
    default: true
    client: true
